In [1]:
import numpy as np

In [3]:
l = [1,2,3,4,5,6]

In [5]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [6]:
l1 = [4,5,6,4,34,"sudh",34.45,True]

In [10]:
a1 =np.array(l1)

In [11]:
a2 = np.array([[1,2,3],[4,5,6]])

In [12]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
a1

array(['4', '5', '6', '4', '34', 'sudh', '34.45', 'True'], dtype='<U32')

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
a1.ndim

1

In [18]:
a2.ndim

2

In [19]:
a3.ndim

3

In [20]:
a1.size

8

In [21]:
a2.size

6

In [22]:
a3.size

9

In [23]:
a1.shape

(8,)

In [24]:
a2.shape

(2, 3)

In [25]:
a3.shape

(1, 3, 3)

In [26]:
a1

array(['4', '5', '6', '4', '34', 'sudh', '34.45', 'True'], dtype='<U32')

In [27]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
np.random.randint(2,50,(3,4))

array([[23, 37, 25, 44],
       [37, 27, 34, 20],
       [40, 48, 44, 42]])

In [37]:
np.random.randint(2,50,(2,3,4))

array([[[ 3,  4, 16,  2],
        [28,  4, 40, 16],
        [43, 22, 19, 42]],

       [[32, 43, 45, 36],
        [ 4, 21, 41, 26],
        [14, 40, 13, 14]]])

In [38]:
np.random.rand(2,3)

array([[0.64542932, 0.40958109, 0.81139128],
       [0.84121283, 0.62356175, 0.80886495]])

In [40]:
a4=np.random.randn(4,4)

In [47]:
#change the shape of data
a4.shape
a4.reshape(2,4,2)

array([[[-0.26867579,  0.13979858],
        [ 0.16859624, -0.43017961],
        [ 0.45745438, -1.59524686],
        [ 0.77045409, -0.41323478]],

       [[-1.16030794,  1.0678333 ],
        [-0.24390741,  0.8967872 ],
        [-0.26130502, -0.07449245],
        [-0.18797348, -0.22752529]]])

In [48]:
a4.reshape(8,2)

array([[-0.26867579,  0.13979858],
       [ 0.16859624, -0.43017961],
       [ 0.45745438, -1.59524686],
       [ 0.77045409, -0.41323478],
       [-1.16030794,  1.0678333 ],
       [-0.24390741,  0.8967872 ],
       [-0.26130502, -0.07449245],
       [-0.18797348, -0.22752529]])

In [49]:
a4.reshape(1,16)

array([[-0.26867579,  0.13979858,  0.16859624, -0.43017961,  0.45745438,
        -1.59524686,  0.77045409, -0.41323478, -1.16030794,  1.0678333 ,
        -0.24390741,  0.8967872 , -0.26130502, -0.07449245, -0.18797348,
        -0.22752529]])

In [50]:
a4.reshape(16,1)

array([[-0.26867579],
       [ 0.13979858],
       [ 0.16859624],
       [-0.43017961],
       [ 0.45745438],
       [-1.59524686],
       [ 0.77045409],
       [-0.41323478],
       [-1.16030794],
       [ 1.0678333 ],
       [-0.24390741],
       [ 0.8967872 ],
       [-0.26130502],
       [-0.07449245],
       [-0.18797348],
       [-0.22752529]])

In [51]:
a4.reshape(2,-1)

array([[-0.26867579,  0.13979858,  0.16859624, -0.43017961,  0.45745438,
        -1.59524686,  0.77045409, -0.41323478],
       [-1.16030794,  1.0678333 , -0.24390741,  0.8967872 , -0.26130502,
        -0.07449245, -0.18797348, -0.22752529]])

In [52]:
a4.reshape(2,-1898)

array([[-0.26867579,  0.13979858,  0.16859624, -0.43017961,  0.45745438,
        -1.59524686,  0.77045409, -0.41323478],
       [-1.16030794,  1.0678333 , -0.24390741,  0.8967872 , -0.26130502,
        -0.07449245, -0.18797348, -0.22752529]])

In [54]:
a4.reshape(1,1,1,1,1,2,2,4)

array([[[[[[[[-0.26867579,  0.13979858,  0.16859624, -0.43017961],
             [ 0.45745438, -1.59524686,  0.77045409, -0.41323478]],

            [[-1.16030794,  1.0678333 , -0.24390741,  0.8967872 ],
             [-0.26130502, -0.07449245, -0.18797348, -0.22752529]]]]]]]])

In [55]:
a1

array(['4', '5', '6', '4', '34', 'sudh', '34.45', 'True'], dtype='<U32')

In [56]:
a1[0]

'4'

In [60]:
a1[2:6]

array(['6', '4', '34', 'sudh'], dtype='<U32')

In [61]:
a1[2:6:2]

array(['6', '34'], dtype='<U32')

In [62]:
a1[::-1]

array(['True', '34.45', 'sudh', '34', '4', '6', '5', '4'], dtype='<U32')

In [63]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [64]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a2[0]

array([1, 2, 3])

In [69]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [70]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [74]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [75]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [77]:
a5 = np.random.randint(2,90,(6,5))

In [78]:
a5

array([[40, 11, 35, 48, 50],
       [53, 54, 87, 13, 57],
       [60, 74, 71, 61, 12],
       [75, 27, 35, 10, 64],
       [18, 25, 53, 40,  2],
       [ 8, 56, 34, 38, 35]])

In [79]:
a5[a5<40]

array([11, 35, 13, 12, 27, 35, 10, 18, 25,  2,  8, 34, 38, 35])

In [80]:
a5

array([[40, 11, 35, 48, 50],
       [53, 54, 87, 13, 57],
       [60, 74, 71, 61, 12],
       [75, 27, 35, 10, 64],
       [18, 25, 53, 40,  2],
       [ 8, 56, 34, 38, 35]])

In [81]:
a5[0,1]=100

In [82]:
a5

array([[ 40, 100,  35,  48,  50],
       [ 53,  54,  87,  13,  57],
       [ 60,  74,  71,  61,  12],
       [ 75,  27,  35,  10,  64],
       [ 18,  25,  53,  40,   2],
       [  8,  56,  34,  38,  35]])

In [89]:
a6 = np.random.randint(0,3,(3,3))

In [90]:
a7= np.random.randint(0,3,(3,3))

In [92]:
a6

array([[0, 2, 1],
       [1, 1, 2],
       [2, 1, 0]])

In [93]:
a7

array([[0, 0, 2],
       [2, 0, 2],
       [0, 1, 1]])

In [94]:
#element by multiplication, this is not matrix multiplication
a6*a7

array([[0, 0, 2],
       [2, 0, 4],
       [0, 1, 0]])

In [95]:
a6@a7

array([[4, 1, 5],
       [2, 2, 6],
       [2, 0, 6]])

In [96]:
a6+100

array([[100, 102, 101],
       [101, 101, 102],
       [102, 101, 100]])

In [97]:
a6*2

array([[0, 4, 2],
       [2, 2, 4],
       [4, 2, 0]])

In [98]:
a6/0

/var/folders/hs/tkrh5wv51hl9c769tvsw6bc00000gn/T/ipykernel_17614/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
/var/folders/hs/tkrh5wv51hl9c769tvsw6bc00000gn/T/ipykernel_17614/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, inf, inf],
       [inf, inf, inf],
       [inf, inf, nan]])

In [99]:
a6**6

array([[ 0, 64,  1],
       [ 1,  1, 64],
       [64,  1,  0]])

In [102]:
a8 = np.zeros((4,4))

In [103]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
a9 =np.ones((4,5))

In [107]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [109]:
#broadcate to every row
a9+ np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [110]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [113]:
#T - transpose 
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [116]:
a6

array([[0, 2, 1],
       [1, 1, 2],
       [2, 1, 0]])

In [117]:
a6.T

array([[0, 1, 2],
       [2, 1, 1],
       [1, 2, 0]])

In [118]:
a5

array([[ 40, 100,  35,  48,  50],
       [ 53,  54,  87,  13,  57],
       [ 60,  74,  71,  61,  12],
       [ 75,  27,  35,  10,  64],
       [ 18,  25,  53,  40,   2],
       [  8,  56,  34,  38,  35]])

In [119]:
np.sqrt(a5)

array([[ 6.32455532, 10.        ,  5.91607978,  6.92820323,  7.07106781],
       [ 7.28010989,  7.34846923,  9.32737905,  3.60555128,  7.54983444],
       [ 7.74596669,  8.60232527,  8.42614977,  7.81024968,  3.46410162],
       [ 8.66025404,  5.19615242,  5.91607978,  3.16227766,  8.        ],
       [ 4.24264069,  5.        ,  7.28010989,  6.32455532,  1.41421356],
       [ 2.82842712,  7.48331477,  5.83095189,  6.164414  ,  5.91607978]])

In [120]:
np.exp(a5)

array([[2.35385267e+17, 2.68811714e+43, 1.58601345e+15, 7.01673591e+20,
        5.18470553e+21],
       [1.04137594e+23, 2.83075330e+23, 6.07603023e+37, 4.42413392e+05,
        5.68572000e+24],
       [1.14200739e+26, 1.37338298e+32, 6.83767123e+30, 3.10429794e+26,
        1.62754791e+05],
       [3.73324200e+32, 5.32048241e+11, 1.58601345e+15, 2.20264658e+04,
        6.23514908e+27],
       [6.56599691e+07, 7.20048993e+10, 1.04137594e+23, 2.35385267e+17,
        7.38905610e+00],
       [2.98095799e+03, 2.09165950e+24, 5.83461743e+14, 3.18559318e+16,
        1.58601345e+15]])

In [121]:
np.log10(a5)

array([[1.60205999, 2.        , 1.54406804, 1.68124124, 1.69897   ],
       [1.72427587, 1.73239376, 1.93951925, 1.11394335, 1.75587486],
       [1.77815125, 1.86923172, 1.85125835, 1.78532984, 1.07918125],
       [1.87506126, 1.43136376, 1.54406804, 1.        , 1.80617997],
       [1.25527251, 1.39794001, 1.72427587, 1.60205999, 0.30103   ],
       [0.90308999, 1.74818803, 1.53147892, 1.5797836 , 1.54406804]])

In [126]:
list(range(0,5,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [139]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [136]:
np.linspace(2,3,num=50,retstep=True) #linearscale

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [137]:
np.logspace(2,4,num=4,base=10) #logrithmic

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [138]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Data visualization 

In [143]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [144]:
cf.go_offline()

In [151]:
df=pd.DataFrame(np.random.randn(100,3),columns=["A","B","C"]) 

In [152]:
df

A         B         C
0  -0.314554 -1.129462 -1.070906
1  -0.790743 -0.941924  0.140626
2   0.491425  0.866972 -0.091922
3   0.130514  0.720733  0.999974
4  -0.058045  0.800220 -0.445378
..       ...       ...       ...
95  1.246845 -1.248005  0.979020
96 -0.236782 -0.577768  0.510938
97 -1.103558  0.497110  0.861637
98 -0.686660 -0.052253 -0.516021
99  0.656232 -0.092217 -0.683063

[100 rows x 3 columns]

In [153]:
df.iplot()

In [154]:
df1=pd.DataFrame(np.random.randint(3,100,(100,1)))

In [155]:
df1.iplot()

In [156]:
df1

0
0   11
1   10
2   48
3   35
4   67
..  ..
95  62
96  64
97  21
98  76
99  46

[100 rows x 1 columns]

In [160]:
df.iplot(x ='A',y='B', mode='markers')

In [162]:
df2=sns.load_dataset('titanic')

In [163]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [165]:
df2.iplot(x ='age',y='fare', mode="markers")

In [166]:
df2.iplot(x ='age',y='pclass', mode="markers")

In [168]:
df2.iplot(x ='fare',y='pclass', mode="markers")

In [169]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [170]:
df2.iplot(kind='bar',x='sex', y='survived')